In [2]:
import numpy as np

# Use of numpy AI and Deeplearnng

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


# upcasting"-string,float int
# mix data types we priority first string change

In [5]:
b=np.array([1,2.5,3])
print(b)

[1.  2.5 3. ]


In [6]:
c=np.array([1,'2',3])
print(c)

['1' '2' '3']


In [7]:
# more than one diamension
a_1=np.array([[1,2],[3,4]])
print(a_1)

[[1 2]
 [3 4]]


In [8]:
# minimum dimensions
a_2=np.array([1,2,3,4,5],ndmin=2)
print(a_2)

[[1 2 3 4 5]]


In [10]:
a_2.shape

(1, 5)

In [13]:
# dtype parameter
b_1=np.array([1,2,3],dtype=complex)
print(b_1)

[1.+0.j 2.+0.j 3.+0.j]


In [14]:
# ndarray.shape
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [21]:
# this resize the nd array
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


# numpy also provides a reshape function to resize an array

In [22]:
d=np.array([[1,2,3],[4,5,6]])
print(d)
print("--------------------------------------------------")
e=d.reshape(3,2)
print(e)

[[1 2 3]
 [4 5 6]]
--------------------------------------------------
[[1 2]
 [3 4]
 [5 6]]


# Returns a new array of specified size and type ,filled with zeros


In [25]:
x=np.zeros((5))
print(x)

[0. 0. 0. 0. 0.]


In [26]:
x=np.zeros((5),dtype=int)
print(x)

[0 0 0 0 0]


In [27]:
x=np.zeros((5,2),dtype=int)
print(x)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [28]:
y=np.ones((5))
print(y)

[1. 1. 1. 1. 1.]


In [30]:
y=np.ones((5),dtype=int)
print(y)

[1 1 1 1 1]


In [31]:
y=np.ones((5,2),dtype=int)
print(y)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [32]:
c=np.eye((5))
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# numpy.empty means dignonal

In [38]:
y=np.empty((5,2),dtype=int)
print(y)

[[         0 1072693248]
 [         0 1072693248]
 [         0 1072693248]
 [         0 1072693248]
 [         0 1072693248]]


# numpy.asarray

In [39]:
x=[1,2,3]
print(x)
print("--------------------------------------")
print(type(x))
print("---------------------------------------")
a=np.asarray(x)
print(a)
print("--------------------------------")
print(type(a))

[1, 2, 3]
--------------------------------------
<class 'list'>
---------------------------------------
[1 2 3]
--------------------------------
<class 'numpy.ndarray'>


# dtype is provided

In [40]:
y=[1,2,3]
print(y)
print("--------------------------------------")
print(type(y))
print("---------------------------------------")
a=np.asarray(x,dtype=float)
print(a)
print("--------------------------------")
print(type(a))

[1, 2, 3]
--------------------------------------
<class 'list'>
---------------------------------------
[1. 2. 3.]
--------------------------------
<class 'numpy.ndarray'>


In [41]:
x=(1,2,3)
a=np.asarray(x)
print(a)

[1 2 3]


# ndarray from list of tuples

In [42]:
x=[(1,2,3),(4,5)]
a=np.asarray(x)
print(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

# numpy.arange

In [43]:
a=np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


# check diamnsional

In [44]:
a=np.arange(24)
print(a.ndim)

1


In [45]:
x=np.arange(5,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


# start and stop parameters set

In [46]:
x=(np.arange(10,22,2)).reshape(2,3)
print(x)

[[10 12 14]
 [16 18 20]]


# numpy.linspace

In [47]:
x=np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [49]:
y=np.linspace(10,20,5,endpoint=False)
print(y)

[10. 12. 14. 16. 18.]


# find retstep value

In [51]:
x=np.linspace(100,500,100,retstep=True)
print(x)

(array([100.        , 104.04040404, 108.08080808, 112.12121212,
       116.16161616, 120.2020202 , 124.24242424, 128.28282828,
       132.32323232, 136.36363636, 140.4040404 , 144.44444444,
       148.48484848, 152.52525253, 156.56565657, 160.60606061,
       164.64646465, 168.68686869, 172.72727273, 176.76767677,
       180.80808081, 184.84848485, 188.88888889, 192.92929293,
       196.96969697, 201.01010101, 205.05050505, 209.09090909,
       213.13131313, 217.17171717, 221.21212121, 225.25252525,
       229.29292929, 233.33333333, 237.37373737, 241.41414141,
       245.45454545, 249.49494949, 253.53535354, 257.57575758,
       261.61616162, 265.65656566, 269.6969697 , 273.73737374,
       277.77777778, 281.81818182, 285.85858586, 289.8989899 ,
       293.93939394, 297.97979798, 302.02020202, 306.06060606,
       310.1010101 , 314.14141414, 318.18181818, 322.22222222,
       326.26262626, 330.3030303 , 334.34343434, 338.38383838,
       342.42424242, 346.46464646, 350.50505051, 354.5