In [19]:
import numpy as np

# Create a 2X2 matrix

In [20]:
matrix1=np.array([[1,3],[5,7]])
print("2X2 Matrix:\n",matrix1)

2X2 Matrix:
 [[1 3]
 [5 7]]


# Create 3X3 matrix

In [21]:
matrix2=np.array([[2,3,5],[7,14,21],[1,3,5]])
print("\n3X3 Matrix:\n",matrix2)


3X3 Matrix:
 [[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]


# Sum of two matrix

In [22]:
a=np.array([[2,3,5],[7,14,21],[1,3,5]])
print(a)
print("-----------------------")
b=np.array([[2,3,5],[7,14,21],[1,3,5]])
print(b)
print("------------------------------")
c=a+b
print(c)

[[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]
-----------------------
[[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]
------------------------------
[[ 4  6 10]
 [14 28 42]
 [ 2  6 10]]


# multiplication -np.dot()

# 1mat col= 2mat row

# 1 3         2  6
# 5 7         4  8
# 1X2+3X4
# 1X6+3X8

In [23]:
mat1=np.array([[1,3],[5,7]])
print(mat1)
print("------------------------")
mat2=np.array([[2,6],[4,8]])
print(mat2)
print("----------------")
# calculate the dot product of two matrics
result=np.dot(mat1,mat2)
print("Matrix X Matrix2:\n",result)

[[1 3]
 [5 7]]
------------------------
[[2 6]
 [4 8]]
----------------
Matrix X Matrix2:
 [[14 30]
 [38 86]]


# Transpose

In [24]:
Matrix3=np.array([[1,3,4],[5,7,9]])
print(Matrix3)
print("----------------------")
# get transpose of matrix
result=np.transpose(Matrix3)
print(result)

[[1 3 4]
 [5 7 9]]
----------------------
[[1 5]
 [3 7]
 [4 9]]


# hstack-concat hori

In [25]:
x=np.array((3,5,7))
print(x)
print("-------------------")
y=np.array((5,7,9))
print(y)
print("-----------------------")
print(np.hstack((x,y)))

[3 5 7]
-------------------
[5 7 9]
-----------------------
[3 5 7 5 7 9]


In [26]:
x2=np.array([[3],[5],[7]])
print(x2)
print("-----------------------")
y2=np.array([[5],[7],[9]])
print(y2)
print("-------------------------")
print(np.hstack((x2,y2)))

[[3]
 [5]
 [7]]
-----------------------
[[5]
 [7]
 [9]]
-------------------------
[[3 5]
 [5 7]
 [7 9]]


# Vstack-concat ver

In [27]:
x1=np.array([3,5,7])
print(x1)
print("-------------------")
y1=np.array([5,7,9])
print(y1)
print("-----------------------")
print(np.vstack((x1,y1)))

[3 5 7]
-------------------
[5 7 9]
-----------------------
[[3 5 7]
 [5 7 9]]


In [28]:
x3=np.array([[3],[5],[7]])
print(x3)
print("-----------------------")
y3=np.array([[5],[7],[9]])
print(y3)
print("-------------------------")
print(np.vstack((x3,y3)))

[[3]
 [5]
 [7]]
-----------------------
[[5]
 [7]
 [9]]
-------------------------
[[3]
 [5]
 [7]
 [5]
 [7]
 [9]]


# Generate Random Number
# np.random.randint

In [31]:
random_number=np.random.randint(0,10)


In [32]:
print(random_number)

4


In [33]:
from numpy import random

In [35]:
random_number1=random.randint(0,10)
print(random_number1)

2


In [38]:
random_number2=np.random.rand()
print(random_number2)

0.22545549876140958


# generate 1D array of 5 random integers between 0 to 9

In [39]:
integer_array=np.random.randint(0,10,5)
print("1D Random Integer Array:\n",integer_array)

1D Random Integer Array:
 [7 7 9 0 4]


# generate 1D array of 5 random float between 0 to 1

In [40]:
float_array=np.random.rand()
print("1D Random float Array:\n",float_array)

1D Random float Array:
 0.36234948791544497


# generate 2D  array of shape(3,4) with  random integers

In [41]:
result=np.random.randint(0,10,(3,4))
print("2D Random Integer Array:\n",result)

2D Random Integer Array:
 [[5 7 0 8]
 [3 0 4 8]
 [4 1 5 1]]


# create an array of integers from 1 to 5

## choose a random num from array

In [42]:
array=np.array([1,2,3,4,5])
print(array)
print("--------------------")
random_choice=np.random.choice(array)
print(random_choice)

[1 2 3 4 5]
--------------------
2
