In [70]:
import numpy as np

# list VS Array

#### 3 benifit of array
#### -Takes less memory
#### -fast
####  -convininent

# -Takes less memory


In [71]:
import time
import sys

In [72]:
sys.getsizeof(1000)

28

In [73]:
l=range(200000)
print(sys.getsizeof(2)*len(l))

5600000


In [74]:
a=np.arange(200000)
a.itemsize

4

In [75]:
a=np.arange(200000)
print(a.itemsize*len(a))

800000


# Fast

In [76]:
a1=range(1000000)
b1=range(1000000)
start=time.time()#start
c1=[(x+y) for x,y in zip(a1,b1)]
print("time taken:",(time.time()-start)*1000)

time taken: 193.94946098327637


In [77]:
a2=np.arange(1000000)
b2=np.arange(1000000)
start=time.time()#start
c2=a2+b2
print("time taken:",(time.time()-start)*1000)

time taken: 3.7724971771240234


In [78]:
start=time.time()#start
start

1733902013.7497692

# convininent

In [79]:
for i in range(1,100):
    print(i*i,end=" ")

1 4 9 16 25 36 49 64 81 100 121 144 169 196 225 256 289 324 361 400 441 484 529 576 625 676 729 784 841 900 961 1024 1089 1156 1225 1296 1369 1444 1521 1600 1681 1764 1849 1936 2025 2116 2209 2304 2401 2500 2601 2704 2809 2916 3025 3136 3249 3364 3481 3600 3721 3844 3969 4096 4225 4356 4489 4624 4761 4900 5041 5184 5329 5476 5625 5776 5929 6084 6241 6400 6561 6724 6889 7056 7225 7396 7569 7744 7921 8100 8281 8464 8649 8836 9025 9216 9409 9604 9801 

In [80]:
n1=np.arange(100)
n2=np.arange(100)
n3=n1*n2
n3

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801])

# Shallow Copy

In [81]:
l=[1,"2",3,4,5]
l1=l
l1

[1, '2', 3, 4, 5]

In [82]:
l=[[1,2,3],[4,5]]
l

[[1, 2, 3], [4, 5]]

In [83]:
l2=l.copy()
l2

[[1, 2, 3], [4, 5]]

In [84]:
l2[0][2]=100
l2

[[1, 2, 100], [4, 5]]

In [85]:
l

[[1, 2, 100], [4, 5]]

# Shallow copy fail for neated list then we use deep copy

In [86]:
print(id(l),print(id(l2)))

2243036192384
2243084503232 None


In [87]:
l=[[1,2,4],[5,6,7]]
l

[[1, 2, 4], [5, 6, 7]]

In [88]:

l2=copy.deepcopy(l)
l2

[[1, 2, 4], [5, 6, 7]]

In [89]:
l2[0][2]=100
l2

[[1, 2, 100], [5, 6, 7]]

In [90]:
l

[[1, 2, 4], [5, 6, 7]]

In [91]:
print(id(l2),id(l))

2243093707776 2243085080064


In [92]:
id(l[0])

2243085048704

In [93]:
id(l[1])

2243085051520

# conditional Selection

In [94]:
a=np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [95]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [96]:
a[a>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [97]:
a[a<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [99]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [100]:
a[a==5]

array([5])

In [101]:
a[a%2 !=0]=0

In [102]:
a

array([ 0,  2,  0,  4,  0,  6,  0,  8,  0, 10,  0, 12,  0, 14,  0, 16,  0,
       18,  0, 20])

# Where condition

In [103]:
a=np.array([1,2,3,4,5,2])
print(a)

[1 2 3 4 5 2]


In [104]:
a.ndim

1

In [105]:
a.shape

(6,)

In [106]:
x=np.where(a==2)
x

(array([1, 5], dtype=int64),)

In [107]:
np.where(a==3)

(array([2], dtype=int64),)

In [108]:
b=np.array([1,2,3,4,5,6])
print(b)


[1 2 3 4 5 6]


In [110]:
np.where(b<4)

(array([0, 1, 2], dtype=int64),)

In [111]:
np.where(b>5)

(array([5], dtype=int64),)

# Search sorted


In [112]:
x=np.array([1,2,3,4,10,11,15])
x

array([ 1,  2,  3,  4, 10, 11, 15])

In [113]:
np.searchsorted(x,8)

4

In [114]:
np.searchsorted(x,12)

6