In [1]:
import numpy as np

In [2]:
x=np.arange(36).reshape(6,6)

In [3]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [4]:
a=np.diag(x)

In [5]:
a

array([ 0,  7, 14, 21, 28, 35])

In [6]:
x=np.array([12,23,34,45,5,56])

In [7]:
np.diag(x)

array([[12,  0,  0,  0,  0,  0],
       [ 0, 23,  0,  0,  0,  0],
       [ 0,  0, 34,  0,  0,  0],
       [ 0,  0,  0, 45,  0,  0],
       [ 0,  0,  0,  0,  5,  0],
       [ 0,  0,  0,  0,  0, 56]])

# seed(25)= this method for fix

In [9]:
from numpy.random import randint as ri

In [10]:
np.random.seed(25)
ri(1,100,(5,6))

array([[ 5, 63, 91, 16, 62, 24],
       [45, 51,  9, 29,  5, 90],
       [32, 70,  2, 40,  4, 89],
       [56,  4, 85, 46,  4,  2],
       [23, 32, 49, 48, 74, 17]])

In [14]:
a=np.random.randint(1,100,30).reshape(5,6)
a

array([[25, 10, 68, 60, 80, 33],
       [96,  6, 57, 37, 84, 20],
       [12, 38, 67, 56, 18, 87],
       [30, 25, 13, 72, 84, 19],
       [63, 28, 47, 34, 56, 75]])

In [24]:
np.random.seed(100)
M=ri(1,100,25).reshape(5,5)

In [25]:
M

array([[ 9, 25, 68, 88, 80],
       [49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35],
       [25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28]])

In [28]:
np.sort(M)#column wise/hori

array([[ 9, 25, 68, 80, 88],
       [11, 49, 53, 95, 99],
       [15, 35, 54, 67, 99],
       [16, 17, 25, 59, 61],
       [ 3, 10, 28, 87, 94]])

In [27]:
np.sort(M,axis=1)# row wise/vertically

array([[ 9, 25, 68, 80, 88],
       [11, 49, 53, 95, 99],
       [15, 35, 54, 67, 99],
       [16, 17, 25, 59, 61],
       [ 3, 10, 28, 87, 94]])

In [29]:
a=ri(1,100,30)
print(a)
print("-------------------------------------")
b=a.reshape(6,5)
print(b)

[ 5 32  2 14 84  5 92 60 68  8 50 48 66 62 15 56 72 81  3 95 20 99 64 54
 28 57 31 49 48 40]
-------------------------------------
[[ 5 32  2 14 84]
 [ 5 92 60 68  8]
 [50 48 66 62 15]
 [56 72 81  3 95]
 [20 99 64 54 28]
 [57 31 49 48 40]]


In [30]:
a.max()# max values in the series or array

99

In [31]:
a.min()# Min values in the series or array

2

In [33]:
a.argmax()# argmax return the index  values of the largest number in the series or array

21

In [34]:
b.max()

99

In [35]:
b.min()

2

In [36]:
b.argmax()

21

In [37]:
b

array([[ 5, 32,  2, 14, 84],
       [ 5, 92, 60, 68,  8],
       [50, 48, 66, 62, 15],
       [56, 72, 81,  3, 95],
       [20, 99, 64, 54, 28],
       [57, 31, 49, 48, 40]])

In [38]:
b.max(axis=0)#column wise

array([57, 99, 81, 68, 95])

In [40]:
b.max(axis=1)#row wise

array([84, 92, 66, 95, 99, 57])

# Accessing of 2D matrixes

In [42]:
x=np.array([[1,2,3,9,10],[12,34,4,5,6],[65,76,7,8,9],[12,34,4,5,6],[65,76,7,8,9]])
print(x)

[[ 1  2  3  9 10]
 [12 34  4  5  6]
 [65 76  7  8  9]
 [12 34  4  5  6]
 [65 76  7  8  9]]


#### x[:,:]# first colon row and second colon column denotes

In [43]:
x[1:3,1:3]

array([[34,  4],
       [76,  7]])

In [45]:
x[1:4,2:4]

array([[4, 5],
       [7, 8],
       [4, 5]])

# 3D matrix

In [46]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [47]:
b=a.reshape(2,4,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [49]:
b.ravel()# all array  falt convert  in the list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
# logspace
a=np.logspace(2,3,num=4)

In [51]:
a

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [52]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [62]:
a=np.array([[1,2],[3,4]])
print(a)
print("-------------------------------------------------")
b=np.array([[5,6],[7,8]])
print(b)
print("-------------------------------------------------")
print(np.concatenate((a,b),axis=0))
print("-------------------------------------------------")
np.concatenate((a,b),axis=1)

[[1 2]
 [3 4]]
-------------------------------------------------
[[5 6]
 [7 8]]
-------------------------------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
-------------------------------------------------


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# split

In [58]:
a=np.arange(12)
np.split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [59]:
str1="Banglore"
str1.split(" ")

['Banglore']

# resize

In [60]:
a=np.array([[1,2,3],[4,5,6]])
np.resize(a,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

# appened

In [66]:
a=np.array([[1,2,3],[4,5,6]])
print("-------------------------------------------------")
print(a)
print("-------------------------------------------------")
print(np.append(a,[[7,8,9]]))


-------------------------------------------------
[[1 2 3]
 [4 5 6]]
-------------------------------------------------
[1 2 3 4 5 6 7 8 9]


# Trigonmetric Functions

In [67]:
a=np.array([0,30,45,60,90])
print(a)
print("---------------------------------")
print(np.sin(a*np.pi/180))

[ 0 30 45 60 90]
---------------------------------
[0.         0.5        0.70710678 0.8660254  1.        ]


In [68]:
np.sin(a)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [70]:
print(np.cos(90*np.pi/180))

6.123233995736766e-17
